[HSDK-295][HSDK-379][HSDK-805] Questionnaire, Preferred Units, object storage docs
huma-engineering/huma-docs pull request #20
Opened 2022-04-18 04:24 UTC by valeriy-huma

https://humatherapeutics.atlassian.net/browse/HSDK-295
https://humatherapeutics.atlassian.net/browse/HSDK-379
https://humatherapeutics.atlassian.net/browse/HSDK-805

2022-04-18 07:40 UTC, andriib-huma approved these changes

2022-04-18 11:52 UTC, andriib-huma requested changes

2022-04-18 11:52 UTC, andriib-huma commented on sdk/Questionnaire/Android.mdx
> +   questionnaireSourceRepository: QuestionnaireSourceRepository,
questionnaireSourceRepository: QuestionnaireSourceRepository is removed from latest sdk

2022-04-25 12:53 UTC, fernandod-huma commented on sdk/Preferred Units/iOS.mdx
> + ### Documentation
@valeriy-huma let's move this under Readme tab

2022-04-25 12:53 UTC, fernandod-huma commented on sdk/Questionnaire/Android.mdx
> + ### Documentation
@valeriy-huma let's move this under Readme tab

2022-04-25 12:53 UTC, fernandod-huma commented on sdk/Questionnaire/iOS.mdx
> +</TabItem>
@valeriy-huma let's move this under Readme tab

2022-04-27 08:21 UTC, andriib-huma approved these changes

2022-04-27 08:21 UTC, merged