[HSDK-387] Added documentation for Huma Caching module
huma-engineering/huma-docs pull request #35
Opened 2022-05-13 11:37 UTC by EvgeniyDavydenko

2022-05-15 08:53 UTC, valeriy-huma requested changes

2022-05-15 08:53 UTC, valeriy-huma commented on sdk/Caching/Android.mdx
> +Huma Android SKD uses Room library which provides an abstraction layer over SQLite to allow fluent database access for persisting data locally.
SDK*

2022-05-15 08:53 UTC, valeriy-huma commented on sdk/Caching/Android.mdx
> +HumaCachingManager is a provider of an interfaces for interaction with local database.
interface*

2022-05-15 08:53 UTC, valeriy-huma commented on sdk/Caching/Android.mdx
> +HumaCachingManager module encapsulates logic of creating instance of `Humadatabase` inheritanced from `RoomDatabase` and defines interfaces for creating DAOs classes and entities converters.
inherited*

2022-05-17 09:53 UTC, EvgeniyDavydenko commented on sdk/Caching/Android.mdx
> +Huma Android SKD uses Room library which provides an abstraction layer over SQLite to allow fluent database access for persisting data locally.
fixed

2022-05-17 09:53 UTC, EvgeniyDavydenko commented on sdk/Caching/Android.mdx
> +HumaCachingManager is a provider of an interfaces for interaction with local database.
fixed

2022-05-17 09:53 UTC, EvgeniyDavydenko commented on sdk/Caching/Android.mdx
> +HumaCachingManager module encapsulates logic of creating instance of `Humadatabase` inheritanced from `RoomDatabase` and defines interfaces for creating DAOs classes and entities converters.
fixed

2022-05-17 09:54 UTC, fernandod-huma requested changes

2022-05-17 10:12 UTC, valeriy-huma approved these changes

2022-05-17 11:46 UTC, EvgeniyDavydenko commented on sdk/Caching/Android.mdx
> +Huma Android SKD uses Room library which provides an abstraction layer over SQLite to allow fluent database access for persisting data locally.
fixed

2022-05-17 11:59 UTC, andriib-huma approved these changes

2022-05-31 11:04 UTC, andriib-huma approved these changes

2022-08-10 13:27 UTC, fernandod-huma approved these changes

2022-08-10 13:28 UTC, merged