Self managed invite navigation
huma-engineering/huma-docs pull request #51
Opened 2022-06-09 07:58 UTC by domm-huma

The initial push of content for Self managed invitation and Navigation.

2022-06-14 10:13 UTC, meldee-huma requested changes

2022-06-14 20:52 UTC, domm-huma commented on data-collection/features/navigation/_category_.json
> +    "label": "Navigation",
Yeah I have that in our structure

![image](https://user-images.githubusercontent.com/102555002/173686512-9e774635-4dfa-4829-bfcc-80a971ed656d.png)

2022-06-14 20:52 UTC, domm-huma commented on data-collection/features/navigation/app/profile.md
> +Patients can receive support in-app by connecting with one of the team in a live chat, and gain access to support documentation.
Yeah, sure thing 👍🏾

2022-06-16 08:26 UTC, meldee-huma approved these changes

2022-06-20 11:58 UTC, closed without merging