New knowledgebase
huma-engineering/huma-docs pull request #64
Opened 2022-08-11 09:33 UTC by catherinemaughan

Conetnt for the Admin portal. I may need to change the order of some of the articles and some of the links will need to be added once I have created the CP and Huma App articles.

2022-08-11 12:00 UTC, meldee-huma requested changes

2022-08-11 12:00 UTC, meldee-huma commented on data-collection/Admin Portal
> +
why do we need this file? Can we delete this 'Admin Portal' file?

2022-08-11 12:07 UTC, meldee-huma commented on data-collection/AdminPortal/Intro.md
> +Once the Organisation and Deployment configurations are complete, Organisation Staff or Access Controllers can be invited to manage it. The Access Controller can then invite an Admin user to manage t
Once the Organisation and Deployment configurations are complete, Admin or Access Controllers can be invited to the Clinician portal to manage the access.

2022-08-30 12:07 UTC, meldee-huma approved these changes

2022-08-30 13:24 UTC, milanof-huma approved these changes

2022-08-30 13:24 UTC, merged